// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  about: dynamic(() => import("./About")),
  doc_body_slice: dynamic(() => import("./DocBodySlice")),
  doc_heading: dynamic(() => import("./DocHeading")),
  hero: dynamic(() => import("./Hero")),
};
